-- ========================================================
-- ORDER MANAGEMENT SCHEMA
-- ========================================================

-- 1. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_id UUID REFERENCES public.consumer_profiles(id) NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, confirmed, shipped, delivered, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) NOT NULL,
    farmer_id UUID REFERENCES public.farmer_profiles(id) NOT NULL, -- Denormalized for easy farmer queries
    quantity INT NOT NULL,
    price_at_purchase NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RLS POLICIES

-- Enable RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- ORDERS POLICIES
-- Consumers can view their own orders
CREATE POLICY "Consumers view own orders" ON public.orders
    FOR SELECT USING (auth.uid() = consumer_id);

-- Consumers can insert their own orders
CREATE POLICY "Consumers create orders" ON public.orders
    FOR INSERT WITH CHECK (auth.uid() = consumer_id);

-- Farmers can view orders containing their products (Bit tricky, usually fulfilled by querying items)
-- For simplicity, let's allow farmers to see orders they are part of (requires join logic or denormalization)
-- Simplified: Farmers see items, Orders is high level.
-- Actually, we might need a distinct 'farmer_orders' view or just query order_items.

-- ORDER ITEMS POLICIES
-- Consumers view their own items (via order link)
CREATE POLICY "Consumers view own items" ON public.order_items
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.consumer_id = auth.uid()
        )
    );

-- Consumers insert items
CREATE POLICY "Consumers insert items" ON public.order_items
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.consumer_id = auth.uid()
        )
    );

-- Farmers view items assigned to them
CREATE POLICY "Farmers view assigned items" ON public.order_items
    FOR SELECT USING (farmer_id = auth.uid());

-- Farmers can update status of items (if we tracked status per item)
-- For now, let's just allow view.
